# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chbedcl < Formula
  desc "Change the Claude model in ~/.claude/settings.json"
  homepage "https://github.com/joaoqalves/chbedcl"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.1.0/chbedcl_1.1.0_darwin_amd64.tar.gz"
      sha256 "090f67f54c3d63fa949349cebb420ab794ab5db6d93f2210d0ebac512539606a"

      define_method(:install) do
        bin.install "chbedcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.1.0/chbedcl_1.1.0_darwin_arm64.tar.gz"
      sha256 "bc11cb3e2f8ac4bf00168add5e23279b73bd72da7cf8194054973cbec16c4130"

      define_method(:install) do
        bin.install "chbedcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.1.0/chbedcl_1.1.0_linux_amd64.tar.gz"
      sha256 "3a428d0922183915a20e8f0c9c89d2a0a53e10c20bd63c2b4bcb42947645f326"
      define_method(:install) do
        bin.install "chbedcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.1.0/chbedcl_1.1.0_linux_arm64.tar.gz"
      sha256 "a6a57ade5f62894897d487ca82efc81e61c8c7e1f226968c9d8fffdb8ad09840"
      define_method(:install) do
        bin.install "chbedcl"
      end
    end
  end

  test do
    assert_match "chbedcl", shell_output("#{bin}/chbedcl --help 2>&1")
  end
end
