# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chbedcl < Formula
  desc "Change the Claude model in ~/.claude/settings.json"
  homepage "https://github.com/joaoqalves/chbedcl"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.0.0/chbedcl_1.0.0_darwin_amd64.tar.gz"
      sha256 "8735df1b3e841096bad34872db3a2c020429110c708d4f0cc47f45c0b4fa1959"

      define_method(:install) do
        bin.install "chbedcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.0.0/chbedcl_1.0.0_darwin_arm64.tar.gz"
      sha256 "8f9c67bedd8da0b2e9ae8b648d389069d516061039a59e3130912f23d767c693"

      define_method(:install) do
        bin.install "chbedcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.0.0/chbedcl_1.0.0_linux_amd64.tar.gz"
      sha256 "5f04c9817da55c084b969a45fb8a5338c51c117eceae7dabccca1555dd708651"
      define_method(:install) do
        bin.install "chbedcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaoqalves/chbedcl/releases/download/v1.0.0/chbedcl_1.0.0_linux_arm64.tar.gz"
      sha256 "22b6e76072d74bc445801397a351af26f4816ba393d5027bce10b6e8e8f6aedd"
      define_method(:install) do
        bin.install "chbedcl"
      end
    end
  end

  test do
    assert_match "chbedcl", shell_output("#{bin}/chbedcl --help 2>&1")
  end
end
